Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/DGM2lines/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
grids = xr.open_dataset(
    "gs://leap-persistent/m2lines-data-gallery/grids.nc", engine="zarr"
)
wet_nan = (
    xr.open_dataset(
        "gs://leap-persistent/m2lines-data-gallery/wet_nan.npy", engine="zarr"
    )
    .to_dataarray()
    .to_numpy()[0]
)

ground_truth = (
    xr.open_dataset(
        "gs://leap-persistent/m2lines-data-gallery/ground_truth.npy", engine="zarr"
    )
    .to_dataarray()
    .to_numpy()[0]
)
model_pred_unet = (
    xr.open_dataset(
        "gs://leap-persistent/m2lines-data-gallery/model_pred_unet.npy", engine="zarr"
    )
    .to_dataarray()
    .to_numpy()[0]
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m grids [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m
[1;32m      2[0m [43m    [49m[38;5;124;43m"[39;49m[38;5;124;43mgs://leap-persistent/m2lines-data-gallery/grids.nc[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mengine[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mzarr[39;49m[38;5;124;43m"[39;49m
[1;32m      3[0m [43m)[49m
[1;32m      4[0m wet_nan [38;5;241m=[39m (
[1;32m      5[0m     xr[38;5;241m.[39mopen_dataset(
[1;32m      6[0m         [38;5;124m"[39m[38;5;124mgs://leap-persistent/m2lines-data-gallery/wet_nan.npy[39m[38;5;124m"[39m, engine[38;5;241m=[39m[38;5;124m"[39m[38;5;124mzarr[39m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m      9[0m     [38;5;241m.[39mto_numpy()[[38;5;241m0[39m]
[1;32m     10[0m )
[1;32m     12[0m ground_truth [38;5;241m=[39m (
[1;32m     13[0m     xr[38;5;241m.[39mopen_dataset(
[1;32m     14[0m         [38;5;124m"[39m[38;5;124mgs://leap-persistent/m2lines-data-gallery/ground_truth.npy[39m[38;5;124m"[39m, engine[38;5;241m=[39m[38;5;124m"[39m[38;5;124mzarr[39m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m     17[0m     [38;5;241m.[39mto_numpy()[[38;5;241m0[39m]
[1;32m     18[0m )

File [0;32m~/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/xarray/backends/api.py:559[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)[0m
[1;32m    556[0m [38;5;28;01mif[39;00m from_array_kwargs [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    557[0m     from_array_kwargs [38;5;241m=[39m {}
[0;32m--> 559[0m backend [38;5;241m=[39m [43mplugins[49m[38;5;241;43m.[39;49m[43mget_backend[49m[43m([49m[43mengine[49m[43m)[49m
[1;32m    561[0m decoders [38;5;241m=[39m _resolve_decoders_kwargs(
[1;32m    562[0m     decode_cf,
[1;32m    563[0m     open_backend_dataset_parameters[38;5;241m=[39mbackend[38;5;241m.[39mopen_dataset_parameters,
[0;32m   (...)[0m
[1;32m    569[0m     decode_coords[38;5;241m=[39mdecode_coords,
[1;32m    570[0m )
[1;32m    572[0m overwrite_encoded_chunks [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moverwrite_encoded_chunks[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)

File [0;32m~/miniconda3/envs/DGM2lines/lib/python3.9/site-packages/xarray/backends/plugins.py:205[0m, in [0;36mget_backend[0;34m(engine)[0m
[1;32m    203[0m     engines [38;5;241m=[39m list_engines()
[1;32m    204[0m     [38;5;28;01mif[39;00m engine [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m engines:
[0;32m--> 205[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    206[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124munrecognized engine [39m[38;5;132;01m{[39;00mengine[38;5;132;01m}[39;00m[38;5;124m must be one of: [39m[38;5;132;01m{[39;00m[38;5;28mlist[39m(engines)[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    207[0m         )
[1;32m    208[0m     backend [38;5;241m=[39m engines[engine]
[1;32m    209[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(engine, [38;5;28mtype[39m) [38;5;129;01mand[39;00m [38;5;28missubclass[39m(engine, BackendEntrypoint):

[0;31mValueError[0m: unrecognized engine zarr must be one of: ['netcdf4', 'store']

